"""- news description

Revision ID: 38b48cce8e94
Revises: be6cc6362d02
Create Date: 2026-02-05 15:05:57.453823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b48cce8e94'
down_revision: Union[str, Sequence[str], None] = 'be6cc6362d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
