"""add category image_path

Revision ID: 3ced8974d52b
Revises: 2bf55249da72
Create Date: 2026-01-28 00:12:18.862636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ced8974d52b'
down_revision: Union[str, Sequence[str], None] = '2bf55249da72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'image_path')
    # ### end Alembic commands ###
