"""Add catalog, brands, characteristics, category tree, orders

Revision ID: 7292477deb40
Revises: 22aa15737cd5
Create Date: 2025-12-12 21:41:06.356284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7292477deb40'
down_revision: Union[str, Sequence[str], None] = '22aa15737cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'number', name='characteristictype'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category_characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_characteristic_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('total_weight_kg', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total_volume_m3', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('brand_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('volume_m3', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('weight_kg', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'weight_kg')
    op.drop_column('products', 'volume_m3')
    op.drop_column('products', 'brand_id')
    op.drop_column('orders', 'total_volume_m3')
    op.drop_column('orders', 'total_weight_kg')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.drop_table('product_characteristic_values')
    op.drop_table('category_characteristics')
    op.drop_table('characteristics')
    op.drop_table('brands')
    # ### end Alembic commands ###
