"""add is_main to product_images

Revision ID: a5ca1a502a38
Revises: db7d5c2562ad
Create Date: 2026-01-07 13:21:09.396782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ca1a502a38'
down_revision: Union[str, Sequence[str], None] = 'db7d5c2562ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ux_product_images_one_main_per_product', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_main IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_product_images_one_main_per_product', table_name='product_images', postgresql_where=sa.text('is_main IS true'))
    op.drop_column('product_images', 'is_main')
    # ### end Alembic commands ###
