"""add category snapshot to order_items

Revision ID: be6cc6362d02
Revises: c7eb17f7d0bc
Create Date: 2026-02-01 18:28:30.059074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6cc6362d02'
down_revision: Union[str, Sequence[str], None] = 'c7eb17f7d0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.execute("""
    UPDATE order_items oi
    SET
      category_id = p.category_id,
      category_name = c.name,
      category_slug = c.slug
    FROM products p
    JOIN categories c ON c.id = p.category_id
    WHERE oi.product_id = p.id
      AND oi.category_name IS NULL;
    """)

    op.add_column('order_items', sa.Column('category_name', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('category_slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'category_slug')
    op.drop_column('order_items', 'category_name')
    op.drop_column('order_items', 'category_id')
    # ### end Alembic commands ###
