"""uq product_characteristic_values

Revision ID: bf765c9af85e
Revises: 1a42ddc4ac86
Create Date: 2026-01-09 11:36:05.469507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf765c9af85e'
down_revision: Union[str, Sequence[str], None] = '1a42ddc4ac86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_characteristic_value', 'product_characteristic_values', ['product_id', 'characteristic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_characteristic_value', 'product_characteristic_values', type_='unique')
    # ### end Alembic commands ###
